// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package orders_test is a generated GoMock package.
package orders_test

import (
	context "context"
	domain "course-go-avito-Orurh/internal/domain"
	delivery "course-go-avito-Orurh/internal/service/delivery"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTxRunner is a mock of TxRunner interface.
type MockTxRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTxRunnerMockRecorder
}

// MockTxRunnerMockRecorder is the mock recorder for MockTxRunner.
type MockTxRunnerMockRecorder struct {
	mock *MockTxRunner
}

// NewMockTxRunner creates a new mock instance.
func NewMockTxRunner(ctrl *gomock.Controller) *MockTxRunner {
	mock := &MockTxRunner{ctrl: ctrl}
	mock.recorder = &MockTxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRunner) EXPECT() *MockTxRunnerMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTxRunner) WithTx(ctx context.Context, fn func(delivery.TxRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxRunnerMockRecorder) WithTx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxRunner)(nil).WithTx), ctx, fn)
}

// MockDeliveryPort is a mock of DeliveryPort interface.
type MockDeliveryPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryPortMockRecorder
}

// MockDeliveryPortMockRecorder is the mock recorder for MockDeliveryPort.
type MockDeliveryPortMockRecorder struct {
	mock *MockDeliveryPort
}

// NewMockDeliveryPort creates a new mock instance.
func NewMockDeliveryPort(ctrl *gomock.Controller) *MockDeliveryPort {
	mock := &MockDeliveryPort{ctrl: ctrl}
	mock.recorder = &MockDeliveryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryPort) EXPECT() *MockDeliveryPortMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockDeliveryPort) Assign(ctx context.Context, orderID string) (domain.AssignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, orderID)
	ret0, _ := ret[0].(domain.AssignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockDeliveryPortMockRecorder) Assign(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockDeliveryPort)(nil).Assign), ctx, orderID)
}

// Unassign mocks base method.
func (m *MockDeliveryPort) Unassign(ctx context.Context, orderID string) (domain.UnassignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, orderID)
	ret0, _ := ret[0].(domain.UnassignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockDeliveryPortMockRecorder) Unassign(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockDeliveryPort)(nil).Unassign), ctx, orderID)
}
