// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package delivery_test is a generated GoMock package.
package delivery_test

import (
	context "context"
	domain "course-go-avito-Orurh/internal/domain"
	delivery "course-go-avito-Orurh/internal/service/delivery"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// ReleaseCouriers mocks base method.
func (m *MockdeliveryRepository) ReleaseCouriers(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCouriers", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseCouriers indicates an expected call of ReleaseCouriers.
func (mr *MockdeliveryRepositoryMockRecorder) ReleaseCouriers(ctx, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCouriers", reflect.TypeOf((*MockdeliveryRepository)(nil).ReleaseCouriers), ctx, now)
}

// WithTx mocks base method.
func (m *MockdeliveryRepository) WithTx(ctx context.Context, fn func(delivery.TxRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockdeliveryRepositoryMockRecorder) WithTx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockdeliveryRepository)(nil).WithTx), ctx, fn)
}

// MockTimeFactory is a mock of TimeFactory interface.
type MockTimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTimeFactoryMockRecorder
}

// MockTimeFactoryMockRecorder is the mock recorder for MockTimeFactory.
type MockTimeFactoryMockRecorder struct {
	mock *MockTimeFactory
}

// NewMockTimeFactory creates a new mock instance.
func NewMockTimeFactory(ctrl *gomock.Controller) *MockTimeFactory {
	mock := &MockTimeFactory{ctrl: ctrl}
	mock.recorder = &MockTimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeFactory) EXPECT() *MockTimeFactoryMockRecorder {
	return m.recorder
}

// Deadline mocks base method.
func (m *MockTimeFactory) Deadline(transport domain.CourierTransportType, now time.Time) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline", transport, now)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockTimeFactoryMockRecorder) Deadline(transport, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockTimeFactory)(nil).Deadline), transport, now)
}
