// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package delivery is a generated GoMock package.
package delivery

import (
	context "context"
	domain "course-go-avito-Orurh/internal/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit), ctx)
}

// Rollback mocks base method.
func (m *MockTx) Rollback(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Rollback", ctx)
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback), ctx)
}

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockdeliveryRepository) BeginTx(ctx context.Context) (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockdeliveryRepositoryMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockdeliveryRepository)(nil).BeginTx), ctx)
}

// DeleteByOrderID mocks base method.
func (m *MockdeliveryRepository) DeleteByOrderID(ctx context.Context, tx Tx, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrderID", ctx, tx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOrderID indicates an expected call of DeleteByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteByOrderID(ctx, tx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteByOrderID), ctx, tx, orderID)
}

// FindAvailableCourierForUpdate mocks base method.
func (m *MockdeliveryRepository) FindAvailableCourierForUpdate(ctx context.Context, tx Tx) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableCourierForUpdate", ctx, tx)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableCourierForUpdate indicates an expected call of FindAvailableCourierForUpdate.
func (mr *MockdeliveryRepositoryMockRecorder) FindAvailableCourierForUpdate(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableCourierForUpdate", reflect.TypeOf((*MockdeliveryRepository)(nil).FindAvailableCourierForUpdate), ctx, tx)
}

// GetByOrderID mocks base method.
func (m *MockdeliveryRepository) GetByOrderID(ctx context.Context, tx Tx, orderID string) (*domain.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, tx, orderID)
	ret0, _ := ret[0].(*domain.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockdeliveryRepositoryMockRecorder) GetByOrderID(ctx, tx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockdeliveryRepository)(nil).GetByOrderID), ctx, tx, orderID)
}

// InsertDelivery mocks base method.
func (m *MockdeliveryRepository) InsertDelivery(ctx context.Context, tx Tx, d *domain.Delivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDelivery", ctx, tx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDelivery indicates an expected call of InsertDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) InsertDelivery(ctx, tx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).InsertDelivery), ctx, tx, d)
}

// ReleaseCouriers mocks base method.
func (m *MockdeliveryRepository) ReleaseCouriers(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCouriers", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseCouriers indicates an expected call of ReleaseCouriers.
func (mr *MockdeliveryRepositoryMockRecorder) ReleaseCouriers(ctx, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCouriers", reflect.TypeOf((*MockdeliveryRepository)(nil).ReleaseCouriers), ctx, now)
}

// UpdateCourierStatus mocks base method.
func (m *MockdeliveryRepository) UpdateCourierStatus(ctx context.Context, tx Tx, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourierStatus", ctx, tx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourierStatus indicates an expected call of UpdateCourierStatus.
func (mr *MockdeliveryRepositoryMockRecorder) UpdateCourierStatus(ctx, tx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourierStatus", reflect.TypeOf((*MockdeliveryRepository)(nil).UpdateCourierStatus), ctx, tx, id, status)
}
