// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

// Package delivery is a generated GoMock package.
package delivery

import (
	domain "course-go-avito-Orurh/internal/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimeFactory is a mock of TimeFactory interface.
type MockTimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTimeFactoryMockRecorder
}

// MockTimeFactoryMockRecorder is the mock recorder for MockTimeFactory.
type MockTimeFactoryMockRecorder struct {
	mock *MockTimeFactory
}

// NewMockTimeFactory creates a new mock instance.
func NewMockTimeFactory(ctrl *gomock.Controller) *MockTimeFactory {
	mock := &MockTimeFactory{ctrl: ctrl}
	mock.recorder = &MockTimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeFactory) EXPECT() *MockTimeFactoryMockRecorder {
	return m.recorder
}

// Deadline mocks base method.
func (m *MockTimeFactory) Deadline(transport domain.CourierTransportType, now time.Time) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline", transport, now)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockTimeFactoryMockRecorder) Deadline(transport, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockTimeFactory)(nil).Deadline), transport, now)
}
